### ISSUE TITLE
Graphdict is a dependency and it has disappeared.

### ISSUE THREAD

**Issue by schmudde** [judepayne/dictim.cookbook#1]
I believe it should be here: https://github.com/judepayne/graphdict.

Interesting library. I was hoping to give it a test drive.

**Comment by judepayne** [comment]
I was in the midst of changing a few things and have not pushed to GitHub in a synchronised manner. Oops.

graphdict became [dictim.graph](https://github.com/judepayne/dictim.graph)

Have pushed the latest on dictim.cookbook just now with fixed dependencies and a new recipe - for producing dot (i.e. graphviz input) rather than d2.

Let me know if you run into any problems.

**Comment by schmudde** [comment]
Nice. It boots now. So I'll close this ticket. 

Just to let you know, certain things won't work because you've changed the dictim interface a bit.

For example, `recipe1.cljc` requires `elem-key`:

https://github.com/judepayne/dictim.cookbook/blob/3366382b17092bcc12a33bcc699562dbdf98aaae/src/dictim/cookbook/recipe1.cljc#L2

But you've moved that and made it private in the dictim library (https://github.com/judepayne/dictim/blob/7d2d9ed4ac126779976f5e3373ebb1f51e28a7f9/src/dictim/flat.cljc#L65). 

Thanks for your work on this. Good, fast graphing is always useful.
